# Generated by Django 6.0.2 on 2026-02-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VizqouteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VizqouteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('contractor', 'Contractor'), ('client', 'Client')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('companyname', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VizqouteQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='vizqoute.vizqouteclient')),
                ('contractorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='vizqoute.vizqouteuser')),
            ],
        ),
        migrations.CreateModel(
            name='VizqoutePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharelink', models.CharField(max_length=255)),
                ('expirydate', models.DateTimeField()),
                ('accesscount', models.IntegerField(default=0)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('quotationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='vizqoute.vizqoutequotation')),
            ],
        ),
        migrations.CreateModel(
            name='VizqouteQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('quotationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vizqoute.vizqoutequotation')),
            ],
        ),
        migrations.CreateModel(
            name='VizqouteRoofingSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roofarea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pitchangle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materialtype', models.CharField(max_length=100)),
                ('laborhours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wastefactor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('quotationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roofingspecs', to='vizqoute.vizqoutequotation')),
            ],
        ),
    ]
