# Generated by Django 6.0.2 on 2026-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizqoute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizqouteclient',
            name='address',
        ),
        migrations.AddField(
            model_name='vizqouteclient',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vizqouteclient',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
